name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]

    services:
      mysql:
        image: mariadb:10.6
        env:
          MARIADB_DATABASE: mysql
          MARIADB_USER: mysql
          MARIADB_PASSWORD: mysql
          MARIADB_ROOT_PASSWORD: mysql
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306

      postgres:
        # Docker Hub image
        image: postgres:14
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  test-success:
    name: Tests
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check build matrix status
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
